FROM golang:1.24-alpine AS builder

RUN apk add --no-cache git

WORKDIR /build

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Build
RUN CGO_ENABLED=0 GOOS=linux go build -o agent ./cmd/agent

# Final stage
FROM alpine:latest

WORKDIR /app

COPY --from=builder /build/agent .

CMD ["/app/agent"]
